### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by intenscia** [Warsow/qfusion#19]
It would be awesome to add a mod + map browser in-game. We have been working on an open mod API (and are working with other open source projects like OpenRA, 0AD).

I setup a demo here in our test environment: https://test.mod.io?user=warsow&key=fac403c862a33b812482f461da7e87e3 which you are welcome to trial if this functionality is of interest. Here to help and answer any questions you may have.

**Comment by dnk777** [comment]
Thanks for the attention to the game! We must tell, its unlikely there will be any mods in foreseeable future. We here are hackers in a good way, we work on things amusing ourselves (like bots + sound coding for me). Other issues get attention only if they are mandatory for implementation of our ideas, or are really vital for the game like critical bugs. Cheers.

**Comment by intenscia** [comment]
Totally understood, also while I use the term "mods" this could mean just "maps"
