### ISSUE TITLE
GetObjectTypeByDecl not found in class asIScriptEngine

### ISSUE THREAD

**Issue by ivanbogomoloff** [Warsow/qfusion#54]
Hello. I can't build.
I cloned this repository by command `git clone --recurse-submodules git@github.com:Warsow/qfusion.git` (and i cloned openal-soft and anglescript to third-party dir) and then i did cmake ./source and then i run cd ./source && make
and during make command i got
```
qfusion-ws/source/game/ai/ascript.cpp:145:58: ошибка: «class asIScriptEngine» не содержит элемента с именем «GetObjectTypeByDecl»; имелось в виду «GetObjectTypeByIndex»?
  145 |         const char *actualTypeName = (GAME_AS_ENGINE())->GetObjectTypeByDecl(actualTypeId)->GetName();
```
I try to find `GetObjectTypeByDecl` in source code, but it fails. 

```
$ grep -nr "GetObjectTypeByDecl" ./
./game/ai/ascript.cpp:109:        asIObjectType *baseType = module->GetObjectTypeByDecl(name);
./game/ai/ascript.cpp:145:        const char *actualTypeName = (GAME_AS_ENGINE())->GetObjectTypeByDecl(actualTypeId)->GetName();
./game/ai/ascript.cpp:146:        int baseTypeId = (GAME_AS_ENGINE())->GetObjectTypeByDecl(name)->GetTypeId();
```

Where i miss something?

**Comment by dnk777** [comment]
Thanks for the report, the cloned setup is seemingly broken, I'm going to look at this issue when it's possible. Please note that you would not be able to run the current master binaries without Warsow 2.6 data files, which are not published yet. You could think of visiting Warsow Discord server (follow the link on https://warsow.net) for further details.

**Comment by dnk777** [comment]
The cloning should be fine for now with regard to submodules setup.
